version: '3.4'

services:
  client:
    image: client
    restart: always
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3030:8080
  server:
    image: server
    restart: always
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - 5050:8080